name = "landing-page-dev"
compatibility_date = "2025-03-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
RESEND_API_KEY="re_ePq9J3jv_DL4BXKJaKWP4SNeZXWcgbNhH"